version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3001:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .    
    image: server-app
    environment:
      - PORT=3001
 
  

